name: Docker Image CI

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main", "feature/*" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: deployments
      run: ./build.sh hackmdio/buildpack:18.16.0-f5fd28b4 hackmdio/runtime:18.16.0-f5fd28b4
